## Pandas analysis

This exercise consists in analyzing a dataset containg timing information from a series of Time-to-Digital-Converters (TDC) implemented in a couple of FPGAs. Each measurement (i.e. each row of the input file) consists of a flag that specifies the type of message ('HEAD', which in this case is always 1), two addresses of the TDC providing the signal ('FPGA' and 'TDC_CHANNEL'), and the timing information ('ORBIT_CNT', 'BX_COUNTER', and 'TDC_MEAS'). Each TDC count corresponds to 25/30 ns, whereas a unit of BX_COUNTER corresponds to 25 ns, and the ORBIT_CNT is increased every 'x' BX_COUNTER. This allows to store the time in a similar way to hours, minutes and seconds.

1\. Create a Pandas DataFrame reading N rows of the 'data_000637.txt' dataset. Choose N to be smaller than or equal to the maximum number of rows and larger that 10k.

2\. Find out the number of BX in a ORBIT (the value 'x').

3\. Find out how much the data taking lasted. You can either make an estimate based on the fraction of the measurements (rows) you read, or perform this check precisely by reading out the whole dataset.

4\. Create a new column with the absolute time in ns (as a combination of the other three columns with timing information).

5\. Replace the values (all 1) of the HEAD column randomly with 0 or 1.

6\. Create a new DataFrame that contains only the rows with HEAD=1.

7\. Make two occupancy plots (one for each FPGA), i.e. plot the number of counts per TDC channel

8\. Use the groupby method to find out the noisy channels, i.e. the TDC channels with most counts (say the top 3)

9\. Count the number of unique orbits. Count the number of unique orbits with at least one measurement from TDC_CHANNEL=139

In [153]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [154]:
#1\. Create a Pandas DataFrame reading N rows of the 'data_000637.txt' dataset. Choose N to be smaller than or equal to the maximum number of rows and larger that 10k.
data=pd.read_csv('data_000637.txt')
data_reduced=data.head(11000)

In [155]:
#2\. Find out the number of BX in a ORBIT (the value 'x').

bx_data=data_reduced[['BX_COUNTER']]
x_value=bx_data.max()+1
print(x_value)

BX_COUNTER    3564
dtype: int64

3\. Find out how much the data taking lasted. You can either make an estimate based on the fraction of the measurements (rows) you read, or perform this check precisely by reading out the whole dataset.

In [156]:
def time_calc(row):
    time=row['ORBIT_CNT'].values[0]*x_value*25+row['BX_COUNTER'].values[0]*25+row['TDC_MEAS'].values[0]*25/30
    return time

first=time_calc(data.head(1))
last=time_calc(data.tail(1))
time_delta=last-first
print(time_delta.values[0])

980416093.3125

4\. Create a new column with the absolute time in ns (as a combination of the other three columns with timing information).

In [181]:
data['abs_time'] = (
    (data['ORBIT_CNT'] * x_value.values * 25) + 
    (data['BX_COUNTER'] * 25) + 
    (data['TDC_MEAS'] * (25 / 30))
)
print(f'The total time is: {data.head(1)['abs_time'].values-data.tail(1)['abs_time'].values} ns')
data

The total time is: [-9.80416093e+08] ns

,HEAD,FPGA,TDC_CHANNEL,ORBIT_CNT,BX_COUNTER,TDC_MEAS,abs_time
0,1,0,123,3869200167,2374,26,3.447457e+14
1,1,0,124,3869200167,2374,27,3.447457e+14
2,1,0,63,3869200167,2553,28,3.447457e+14
3,1,0,64,3869200167,2558,19,3.447457e+14
4,1,0,64,3869200167,2760,25,3.447457e+14
...,...,...,...,...,...,...,...
1310715,1,0,62,3869211171,762,14,3.447467e+14
1310716,1,1,4,3869211171,763,11,3.447467e+14
1310717,1,0,64,3869211171,764,0,3.447467e+14
1310718,1,0,139,3869211171,769,0,3.447467e+14
1310719,1,0,61,3869211171,762,18,3.447467e+14

5\. Replace the values (all 1) of the HEAD column randomly with 0 or 1.

In [216]:
data['HEAD'] = np.random.randint(0, 2, size=len(data))
data

,HEAD,FPGA,TDC_CHANNEL,ORBIT_CNT,BX_COUNTER,TDC_MEAS,abs_time
0,1,0,123,3869200167,2374,26,3.447457e+14
1,0,0,124,3869200167,2374,27,3.447457e+14
2,0,0,63,3869200167,2553,28,3.447457e+14
3,1,0,64,3869200167,2558,19,3.447457e+14
4,0,0,64,3869200167,2760,25,3.447457e+14
...,...,...,...,...,...,...,...
1310715,0,0,62,3869211171,762,14,3.447467e+14
1310716,1,1,4,3869211171,763,11,3.447467e+14
1310717,1,0,64,3869211171,764,0,3.447467e+14
1310718,0,0,139,3869211171,769,0,3.447467e+14
1310719,1,0,61,3869211171,762,18,3.447467e+14

6\. Create a new DataFrame that contains only the rows with HEAD=1.

In [225]:
data_head_1 = data[data['HEAD'] == 1].copy()
data_head_1

,HEAD,FPGA,TDC_CHANNEL,ORBIT_CNT,BX_COUNTER,TDC_MEAS,abs_time
0,1,0,123,3869200167,2374,26,3.447457e+14
3,1,0,64,3869200167,2558,19,3.447457e+14
6,1,0,61,3869200167,2772,14,3.447457e+14
9,1,0,60,3869200167,2788,7,3.447457e+14
11,1,0,64,3869200167,2786,19,3.447457e+14
...,...,...,...,...,...,...,...
1310712,1,1,35,3869211171,429,4,3.447467e+14
1310714,1,0,60,3869211171,762,2,3.447467e+14
1310716,1,1,4,3869211171,763,11,3.447467e+14
1310717,1,0,64,3869211171,764,0,3.447467e+14
1310719,1,0,61,3869211171,762,18,3.447467e+14